# Site settings
title: Art for All
email: stliu18@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Art 4 All is an interactive and educational platform for public engagement at art museums
baseurl: "/artforall" # the subpath of your site, e.g. /blog/
url: "http://stephanieliu.me" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build setting
markdown: kramdown
